### ISSUE TITLE
Display 'Known formats' as leading column on overview

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/format-support-table#19]
Some confusion caused by

![image](https://github.com/catalystneuro/format-support-table/assets/51133164/c0f46111-4cc4-457c-bc4d-8a6f43b2cb99)

could be resolved by counting the total number of known 'formats' as the target for each modality

Also, just like how the GUIDE divisor is the interface existence in NeuroConv, the divisor for SpikeInterface should be the presence of a Neo RawIO

**Comment by garrettmflynn** [comment]
I've created a system for associating certain totals with the counts from other columns—though we should try to make sure those relationships actually hold in the table.

For instance, RawMCS (.h5) has a valid Spike Interface Extractor—but no entries for the Neo RawIO.

<img width="813" alt="Screenshot 2023-10-16 at 3 35 39 PM" src="https://github.com/catalystneuro/format-support-table/assets/46533749/5085136d-7a92-428a-8897-830254b189e4">
