### ISSUE TITLE
Dynamic counters

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/format-support-table#2]
Depending on storage structure we end up deciding on from #1, it would be nice to have a dynamic reporter of...

i) number of formats (total and by modality)
ii) number of versions (total, by modality, and by format)

**Comment by garrettmflynn** [comment]
Any ideas how you'd like this to look? Should be easy enough to compute and print to the console

**Comment by CodyCBakerPhD** [comment]
I can put it together now that all the data is in JSON format

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Is there a way to add an extra tab to the table, or some kind of global dashboard at the time that displays the total number of formats? I can ofc add Python functions for counting that if needed but TBH it's just the # of unique names in the name column across all tabs so maybe easier to keep everything web based here?

Just not sure how to insert the calculated values into a dynamic counter like that in the HTML itself
