### ISSUE TITLE
Move outer assets to inner organization

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/format-support-table#36]
@garrettmflynn When you get a moment

There are several files in the root of the repo that look like they could be scoped into their own folder (such as styles?)

These include...

https://github.com/catalystneuro/format-support-table/blob/main/create.js

https://github.com/catalystneuro/format-support-table/blob/main/index.html

https://github.com/catalystneuro/format-support-table/blob/main/open.svg

https://github.com/catalystneuro/format-support-table/blob/main/style.css

**Comment by garrettmflynn** [comment]
There are a wide variety of different structures that people use to organize their files using Vite—though the `index.html` file is (almost) always at the root of the repo.

The current system is used for the [Vite Vanilla demo](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vanilla), whereas a `src`-scoped system is used for the [Vanilla TS demo](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vanilla-ts).

In the related PR, I've opted for the latter.

**Comment by garrettmflynn** [comment]
Let me know if you'd prefer anything in a different place. At the end of the day, this choice is relatively arbitrary—except for changing the location of the `index.html` file, which would require significant changes to the configuration.

**Comment by CodyCBakerPhD** [comment]
The `index` part makes a bit more sense; the PR does clean the rest up more nicely
